#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_DATA_DIRS="$HOME"/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
export XDG_STATE_HOME="$HOME"/.local/state

export GOPATH="$XDG_DATA_HOME"/go
export SXHKD_SHELL=/usr/bin/dash

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/share/JetBrains/Toolbox/scripts"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.asdf/bin"
export PATH="$PATH:$HOME/.asdf/shims"
export PATH="$PATH:$GOPATH/bin"

export GOPRIVATE="github.com/kevincali/*,github.com/Clarilab/*,dev.azure.com"

export EDITOR="$(which hx)"
export VISUAL="$EDITOR"
export TERMINAL="$(which wezterm)"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
