#!/usr/bin/env bash
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state

export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland

export GPG_TTY=$(tty)

export GOPATH="$XDG_DATA_HOME"/go
export GOPRIVATE="github.com/kevincali/*,github.com/Clarilab/*,dev.azure.com"

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.asdf/bin"
export PATH="$PATH:$HOME/.asdf/shims"
export PATH="$PATH:$GOPATH/bin"

export EDITOR="$(which helix)"
export VISUAL="$EDITOR"
export TERMINAL="$(which alacritty)"
