# Adjust bluetooth audio devices
# https: //wiki.archlinux.org/title/WirePlumber#Changing_a_device/node_property
# Getting device.name:
#   wpctl status --nick | grep bluez
#   wpctl inspect $ID

monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "bluez_card.98_8E_79_00_52_6F"
      }
    ]
    actions = {
      update-props = {
        device.description = "Headphones"
      }
    }
  },{
    matches = [
      {
        device.name = "bluez_card.94_DB_56_52_D0_86"
      }
    ]
    actions = {
      update-props = {
        device.description = "Sony Headphones"
      }
    }
  }
]

# Fix HSP/HFP issues
# https://wiki.archlinux.org/title/Bluetooth_headset#Disable_PipeWire_HSP/HFP_profile
wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
}
monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink a2dp_source ]
}
