# Adjust wired audio devices
# https: //wiki.archlinux.org/title/WirePlumber#Changing_a_device/node_property
# Getting node.nick:
#   wpctl status --nick

monitor.alsa.rules = [
  {
    matches = [
      {
        node.nick = "USB SPDIF Adapter"
      }
    ]
    actions = {
      update-props = {
        node.description = "Speakers"
      }
    }
  },
  {
    matches = [
      {
        node.nick = "SONY TV  *30"
      }
      {
        node.nick = "HDMI 0"
      }
      {
        node.nick = "HDMI 1"
      }
    ]
    actions = {
      update-props = {
        node.description = "TV"
      }
    }
  },
  {
    matches = [
      {
        node.nick = "LG TV SSCR2"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  },
  {
    matches = [
      {
        node.nick = "RØDE VideoMic GO II"
      }
    ]
    actions = {
      update-props = {
        node.description = "Microphone"
      }
    }
  }
]
