#!/usr/bin/env sh
# This script adds commented `Co-authored-by: ` entries to the commit message

# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
# SHA1=$3

# Only add custom message when there is no commit source
# ($COMMIT_SOURCE is empty). Otherwise, keep the default message
# proposed by Git. Possible commit source: message, template,
# merge, squash or commit. See https://git-scm.com/docs/githooks

if [ -z "$COMMIT_SOURCE" ]
then 
  while read -r line; 
  do
    printf '#Co-authored-by: '>> "$COMMIT_MSG_FILE"
    echo "$line" >> "$COMMIT_MSG_FILE"
  done < "$HOME"/.git_coauthors 
fi
