#!/usr/bin/env sh

##################
#### MONITORS ####
##################
# bug workaround:
# bspc sometimes shows less monitors than xrandr
# running xrandr --auto seems to fix it
BSPC_MONITOR_COUNT=$(bspc query --monitors | wc -l)
XRANDR_MONITOR_COUNT=$(xrandr --query | grep -c " connected")
if [ "$BSPC_MONITOR_COUNT" != "$XRANDR_MONITOR_COUNT" ]; then
   xrandr --auto
fi

MAIN=$(xrandr | awk '$3 ~ 3840x1600 {print $1}')
SECONDARY=$(xrandr | awk '$3 ~ 2560x1440 {print $1}')
LAPTOP="eDP-1"

case "$BSPC_MONITOR_COUNT" in
    2) bspc monitor "$LAPTOP" -d 1 2
       bspc monitor "$MAIN"  -d 3 4 5 6 7 8 9
       ;;
    3) bspc monitor "$LAPTOP" -d 1 2
       bspc monitor "$MAIN"  -d 3 4 5 6
       bspc monitor "$SECONDARY" -d 7 8 9
       ;;
    *) bspc monitor -d 1 2 3 4 5 6 7 8 9
       ;;
esac

################
#### CONFIG ####
################
bspc config automatic_scheme            longest_side
bspc config initial_polarity            second_child
bspc config border_width                2
bspc config window_gap                  0
bspc config top_padding                 32
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config split_ratio                 0.50
bspc config single_monocle              true
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true
bspc config ignore_ewmh_fullscreen      none

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner

bspc wm --reorder-monitors "$LAPTOP" "$MAIN" "$SECONDARY"

################
#### COLORS ####
################
bspc config normal_border_color		"#4c566a"
bspc config active_border_color	  "#1e1e1e"
bspc config focused_border_color	"#ea7d7d"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

###############
#### RULES ####
###############
case "$BSPC_MONITOR_COUNT" in
    2)
      bspc rule -a Slack desktop=^1
      bspc rule -a "TeamSpeak 3" desktop=^1
      bspc rule -a TelegramDesktop desktop=^1
      bspc rule -a discord desktop=^2
      bspc rule -a Spotify desktop=^2
      bspc rule -a browser2 desktop=^3
      bspc rule -a browser3 desktop=^4
      bspc rule -a browser1 desktop=^5
      ;;
    *)
      bspc rule -a Slack desktop=^1
      bspc rule -a browser2 desktop=^3
      bspc rule -a browser3 desktop=^4
      bspc rule -a browser1 desktop=^5
      bspc rule -a "TeamSpeak 3" desktop=^7
      bspc rule -a TelegramDesktop desktop=^7
      bspc rule -a discord desktop=^7
      bspc rule -a Spotify desktop=^7
      ;;
esac

